
import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Separator } from '@/components/ui/separator';

const Disclaimer = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      
      <main className="flex-grow pt-20 pb-16">
        <div className="container mx-auto px-4 mt-8">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center max-w-3xl mx-auto mb-12"
          >
            <h1 className="text-3xl md:text-4xl font-heading font-bold mb-4">Disclaimer</h1>
            <p className="text-lg text-muted-foreground">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </motion.div>
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="max-w-3xl mx-auto prose prose-slate prose-headings:font-heading"
          >
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Website Disclaimer</h2>
              <p className="text-muted-foreground mb-4">
                The information provided by QuizzenFactory ("we," "us," or "our") on quizzenfactory.com (the "Site") is for general informational and educational purposes only. All information on the Site is provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.
              </p>
              <p className="text-muted-foreground">
                Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the site or reliance on any information provided on the site. Your use of the site and your reliance on any information on the site is solely at your own risk.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">AI-Generated Content Disclaimer</h2>
              <p className="text-muted-foreground mb-4">
                QuizzenFactory utilizes artificial intelligence technology (specifically Google's Gemini AI) to generate quiz content. Please be aware of the following:
              </p>
              
              <ul className="list-disc pl-5 mb-4 text-muted-foreground">
                <li>The quizzes and questions generated by our AI system are intended for educational entertainment purposes only.</li>
                <li>While we strive for accuracy, AI-generated content may contain errors, inaccuracies, or outdated information.</li>
                <li>The AI generates content based on patterns in its training data and cannot verify the factual accuracy of every statement.</li>
                <li>Users should independently verify any important information obtained from our quizzes.</li>
                <li>We implement filters and safeguards, but inappropriate or biased content may occasionally be generated despite our best efforts.</li>
              </ul>
              
              <p className="text-muted-foreground">
                By using our service, you acknowledge and accept these limitations of AI-generated content.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">External Links Disclaimer</h2>
              <p className="text-muted-foreground mb-4">
                The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.
              </p>
              <p className="text-muted-foreground">
                We do not warrant, endorse, guarantee, or assume responsibility for the accuracy or reliability of any information offered by third-party websites linked through the Site or any website or feature linked in any banner or other advertising. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Professional Disclaimer</h2>
              <p className="text-muted-foreground">
                The Site cannot and does not contain educational advice. The educational information is provided for general informational and educational purposes only and is not a substitute for professional advice. Accordingly, before taking any actions based upon such information, we encourage you to consult with the appropriate professionals. We do not provide any kind of educational advice. The use or reliance of any information contained on the Site is solely at your own risk.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Fair Use Disclaimer</h2>
              <p className="text-muted-foreground mb-4">
                This Site may contain copyrighted material the use of which has not always been specifically authorized by the copyright owner. We are making such material available in our efforts to advance understanding of educational, scientific, and historical topics. We believe this constitutes a "fair use" of any such copyrighted material as provided for in section 107 of the US Copyright Law.
              </p>
              <p className="text-muted-foreground">
                If you wish to use copyrighted material from this site for purposes of your own that go beyond fair use, you must obtain permission from the copyright owner.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Testimonials Disclaimer</h2>
              <p className="text-muted-foreground">
                The Site may contain testimonials by users of our services. These testimonials reflect the real-life experiences and opinions of such users. However, the experiences are personal to those particular users, and may not necessarily be representative of all users of our services. We do not claim, and you should not assume, that all users will have the same experiences. Your individual results may vary.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div>
              <h2 className="text-2xl font-bold mb-4">Contact Us</h2>
              <p className="text-muted-foreground mb-4">
                If you have any questions about this Disclaimer, please contact us:
              </p>
              <ul className="list-disc pl-5 text-muted-foreground">
                <li>By email: <a href="mailto:contact@piyushmaji.com" className="text-primary hover:underline">contact@piyushmaji.com</a></li>
                <li>By visiting the Developer page on our website</li>
              </ul>
            </div>
          </motion.div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default Disclaimer;
