
import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Separator } from '@/components/ui/separator';

const TermsOfService = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      
      <main className="flex-grow pt-20 pb-16">
        <div className="container mx-auto px-4 mt-8">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center max-w-3xl mx-auto mb-12"
          >
            <h1 className="text-3xl md:text-4xl font-heading font-bold mb-4">Terms of Service</h1>
            <p className="text-lg text-muted-foreground">
              Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </motion.div>
          
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="max-w-3xl mx-auto prose prose-slate prose-headings:font-heading"
          >
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Introduction</h2>
              <p className="text-muted-foreground mb-4">
                Welcome to QuizzenFactory. These Terms of Service govern your access to and use of the QuizzenFactory website, including any content, functionality, and services offered on or through the website.
              </p>
              <p className="text-muted-foreground">
                Please read these Terms of Service carefully before you start to use the website. By using the website, you accept and agree to be bound and abide by these Terms of Service. If you do not want to agree to these Terms of Service, you must not access or use the website.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Use of the Service</h2>
              <p className="text-muted-foreground mb-4">
                QuizzenFactory provides an AI-powered quiz generation service that allows users to create custom quizzes on various topics and access daily generated quizzes. By using our service, you agree to:
              </p>
              
              <ul className="list-disc pl-5 mb-4 text-muted-foreground">
                <li>Use the service only for lawful purposes and in accordance with these Terms of Service</li>
                <li>Not use the service in any way that violates any applicable federal, state, local, or international law or regulation</li>
                <li>Not attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of the service</li>
                <li>Not use the service to generate harmful, offensive, or inappropriate content</li>
              </ul>
              
              <p className="text-muted-foreground">
                We limit custom quiz generation to once every 10 minutes to ensure fair access to the service for all users. This time limit is non-negotiable and attempts to circumvent it are prohibited.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Intellectual Property</h2>
              <p className="text-muted-foreground mb-4">
                The QuizzenFactory website and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by QuizzenFactory, its licensors, or other providers of such material and are protected by copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.
              </p>
              
              <h3 className="text-xl font-semibold mb-3">Quiz Content</h3>
              <p className="text-muted-foreground mb-4">
                Quizzes generated by our service are for personal educational and entertainment use only. You may use the generated quizzes for personal or educational purposes, but you may not:
              </p>
              <ul className="list-disc pl-5 mb-4 text-muted-foreground">
                <li>Claim ownership of the generated content</li>
                <li>Redistribute or republish the generated content commercially without our permission</li>
                <li>Use the generated content to train AI systems or create competing services</li>
              </ul>
              
              <p className="text-muted-foreground">
                The accuracy of generated quiz content cannot be guaranteed, as it is created by an AI system. While we strive for accuracy, users should verify any important information independently.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Limitations of Liability</h2>
              <p className="text-muted-foreground mb-4">
                In no event will QuizzenFactory, its affiliates, or their licensors, service providers, employees, agents, officers, or directors be liable for damages of any kind, under any legal theory, arising out of or in connection with your use, or inability to use, the website, any websites linked to it, any content on the website or such other websites, including any direct, indirect, special, incidental, consequential, or punitive damages.
              </p>
              <p className="text-muted-foreground">
                This includes but is not limited to, personal injury, pain and suffering, emotional distress, loss of revenue, loss of profits, loss of business or anticipated savings, loss of use, loss of goodwill, loss of data, and whether caused by tort (including negligence), breach of contract, or otherwise, even if foreseeable.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Disclaimer of Warranties</h2>
              <p className="text-muted-foreground mb-4">
                You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or the website will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data.
              </p>
              <p className="text-muted-foreground mb-4">
                The service and its content are provided on an "as is" and "as available" basis, without any warranties of any kind, either express or implied. Neither QuizzenFactory nor any person associated with QuizzenFactory makes any warranty or representation with respect to the completeness, security, reliability, quality, accuracy, or availability of the service.
              </p>
              <p className="text-muted-foreground">
                The foregoing does not affect any warranties that cannot be excluded or limited under applicable law.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">AI-Generated Content Disclaimer</h2>
              <p className="text-muted-foreground mb-4">
                QuizzenFactory uses Google's Gemini AI technology to generate quiz content. While we strive to provide accurate and high-quality content, please be aware:
              </p>
              <ul className="list-disc pl-5 mb-4 text-muted-foreground">
                <li>Quiz questions and answers are generated by AI and may occasionally contain factual errors or inaccuracies</li>
                <li>The service should be used primarily for educational entertainment</li>
                <li>Users should not rely on the generated content for critical decisions or as the sole source of information on any topic</li>
                <li>We cannot guarantee that all content will be appropriate for all ages, though we implement safeguards to minimize inappropriate content</li>
              </ul>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Modifications to the Service</h2>
              <p className="text-muted-foreground">
                We reserve the right to withdraw or amend this website, and any service or material we provide on the website, in our sole discretion without notice. We will not be liable if for any reason all or any part of the website is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the website, or the entire website, to users.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div className="mb-8">
              <h2 className="text-2xl font-bold mb-4">Changes to the Terms of Service</h2>
              <p className="text-muted-foreground">
                We may revise and update these Terms of Service from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the website thereafter. Your continued use of the website following the posting of revised Terms of Service means that you accept and agree to the changes.
              </p>
            </div>
            
            <Separator className="my-8" />
            
            <div>
              <h2 className="text-2xl font-bold mb-4">Contact Information</h2>
              <p className="text-muted-foreground mb-4">
                Questions or comments about the website or these Terms of Service may be directed to:
              </p>
              <ul className="list-disc pl-5 text-muted-foreground">
                <li>By email: <a href="mailto:contact@piyushmaji.com" className="text-primary hover:underline">contact@piyushmaji.com</a></li>
                <li>By visiting the Developer page on our website</li>
              </ul>
            </div>
          </motion.div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
};

export default TermsOfService;
